CREATE TABLE IF NOT EXISTS PlayerPositions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    playerID VARCHAR(255) NOT NULL,
    posX FLOAT NOT NULL,
    posY FLOAT NOT NULL,
    posZ FLOAT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
